vnet:
  cidr: 10.0.0.0/16
  subnets:
  - name: subnet1
    prefix: 10.0.1.0/24
  - name: subnet2
    prefix: 10.0.2.0/24
    service_endpoints:
    - Microsoft.Storage
    - Microsoft.Sql
    delegations:
      Microsoft.Sql.managedInstances:
        service_name: Microsoft.Sql/managedInstances
        service_actions:
        - Microsoft.Network/virtualNetworks/subnets/join/action
        - Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action
        - Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action
  - name: subnet3
    prefix: 10.0.3.0/24
    service_endpoints:
    - Microsoft.AzureActiveDirectory
