apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .Values.name }}-vault-dynamic-secret
  namespace: {{ .Release.Namespace }}
spec:
  mount: {{ .Values.vault.dynamicSecret.mount }}
  path: {{ .Values.vault.dynamicSecret.path }}
  destination:
    name: {{ .Values.vault.dynamicSecret.destination.name }}
    create: {{ .Values.vault.dynamicSecret.destination.create }}
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Values.name }}-deployment
  refreshAfter: {{ .Values.vault.dynamicSecret.refreshAfter }}
  vaultAuthRef: {{ .Values.name }}-vault-auth
