apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.name }}-vault-static-secret
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: {{ .Values.vault.staticSecret.mount }}
  path: {{ .Values.vault.staticSecret.path }}
  destination:
    name: {{ .Values.vault.staticSecret.destination.name }}
    create: {{ .Values.vault.staticSecret.destination.create }}
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Values.name }}-deployment
  refreshAfter: {{ .Values.vault.staticSecret.refreshAfter }}
  vaultAuthRef: {{ .Values.name }}-vault-auth
